dingtalk_aitable:
  # Create your own AI Table from the template, then paste the new table URL here.
  # Template:
  # https://alidocs.dingtalk.com/i/nodes/P7QG4Yx2Jp7ePkDPCgBNyEnEV9dEq3XD?corpId=ding1eff7bf4d86437eb35c2f4657eb6378f&iframeQuery=applicationId%3DKY9tlWg5NEHgfs8WT6IO2%26entrance%3Ddata
  url: ""

report_defaults:
  invoice_title_search: "021"
  invoice_title: "深圳卓正光锥科技有限公司-021"
  cost_center_1: "集团职能部门"
  cost_center_2: "软件研发部"
  cost_center_3: "软件研发部"
  is_r_and_d_project: "否"
  travel_type: "其他（请在事由处说明）"
  travel_scope_default: "跨省、直辖市"
  payment_receiver: "current_user"
